### PR TITLE
toponav2 fixes

### PR DESCRIPTION
**Pull request by gpdas**
This fixes issues with topological navigation 2.
1. `roscore` 
2. `roslaunch uol_cmp9767m_base thorvald-sim.launch`
3. `roslaunch uol_cmp9767m_tutorial topo_nav_central.launch` -- launches the topological and metric maps
4. `roslaunch uol_cmp9767m_tutorial topo_nav_robot.launch`  -- launches robot specific toponav2 nodes

Known issue:
 - [ ] robot_model in rviz complains about some frames (legs and wheels) not in the tf tree.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Much appreciated, but this PR is too substantial to be used by the students this year. They may well have used the previous launch file as a template to make their own for their submission and I can't bother them now (4 hours before submission) with a new one. We should rather move to toponav2 properly for next time.

**Comment by gpdas** [comment]
@marc-hanheide 
If it is too close to submission, I would suggest to keep it for next batch. 

In fact, there are not many changes. I mainly split one launch file into two - for avoiding duplicate launching of common nodes. And added tmap2 maps.

**Comment by adambinch** [comment]
Tested this. Works fine! :)

**Comment by marc-hanheide** [comment]
Thanks, but these have now been superseded by recent fixes, mainly in 671d196643e2eb54eeb3cd2d066bfb849a107119

**Pull request closed without merging**
